export const FBR_SANDBOX_SCENARIOS = [
  { code: "SN001", label: "Goods at standard rate (Registered Buyer)" },
  { code: "SN002", label: "Goods at standard rate (Unregistered Buyer)" },
  { code: "SN003", label: "Steel melting and re-rolling" },
  { code: "SN004", label: "Ship breaking" },
  { code: "SN005", label: "Goods at Reduced Rate" },
  { code: "SN006", label: "Exempt goods" },
  { code: "SN007", label: "Goods at zero-rate" },
  { code: "SN008", label: "3rd Schedule Goods" },
  { code: "SN009", label: "Cotton ginners" },
  { code: "SN010", label: "Telecommunication services" },
  { code: "SN011", label: "Toll Manufacturing" },
  { code: "SN012", label: "Petroleum Products" },
  { code: "SN013", label: "Electricity Supply to Retailers" },
  { code: "SN014", label: "Gas to CNG stations" },
  { code: "SN015", label: "Mobile Phones" },
  { code: "SN016", label: "Processing/Conversion of Goods" },
  { code: "SN017", label: "Goods (FED in ST Mode)" },
  { code: "SN018", label: "Services (FED in ST Mode)" },
  { code: "SN019", label: "Services (ICTO)" },
  { code: "SN020", label: "Electric Vehicle" },
  { code: "SN021", label: "Cement/Concrete Block" },
  { code: "SN022", label: "Potassium Chlorate" },
  { code: "SN023", label: "CNG Sales" },
  { code: "SN024", label: "Goods as per SRO.297(I)/2023" },
  { code: "SN025", label: "Non-Adjustable Supplies" },
  { code: "SN026", label: "Retailer Sale (Standard Rate)" },
  { code: "SN027", label: "Retailer Sale (3rd Schedule Goods)" },
  { code: "SN028", label: "Retailer Sale (Reduced Rate)" },
] as const;

export type FbrSandboxScenarioCode = (typeof FBR_SANDBOX_SCENARIOS)[number]["code"];
