"""add fbr further tax to documents and lines

Revision ID: 233418962826
Revises: a5f4c1a25cde
Create Date: 2026-07-24 23:58:40.288398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233418962826'
down_revision: Union[str, None] = 'a5f4c1a25cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_lines', sa.Column('further_tax', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('further_tax_total', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'further_tax_total')
    op.drop_column('document_lines', 'further_tax')
    # ### end Alembic commands ###
