"""Counter sale: contact details and till on documents

Revision ID: 39bbb9ad5c50
Revises: 5631ce6e038c
Create Date: 2026-08-07 19:30:55.337501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bbb9ad5c50'
down_revision: Union[str, None] = '5631ce6e038c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('contact_name', sa.String(length=150), nullable=True))
    op.add_column('documents', sa.Column('contact_phone', sa.String(length=40), nullable=True))
    op.add_column('documents', sa.Column('paid_through_account_id', sa.Integer(), nullable=True))
    op.create_index('ix_documents_org_contact_phone', 'documents', ['org_id', 'contact_phone'], unique=False)
    op.create_foreign_key(
        'fk_documents_paid_through_account_id_accounts', 'documents', 'accounts',
        ['paid_through_account_id'], ['id'], ondelete='RESTRICT',
    )
    # ### end Alembic commands ###
    op.drop_constraint('ck_documents_payment_fields_type', 'documents', type_='check')
    op.create_check_constraint(
        'ck_documents_payment_fields_type',
        'documents',
        "type IN ('invoice', 'bill', 'sales_receipt') OR "
        "(amount_paid = 0 AND amount_credited = 0 AND payment_status = 'unpaid')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_documents_payment_fields_type', 'documents', type_='check')
    op.create_check_constraint(
        'ck_documents_payment_fields_type',
        'documents',
        "type IN ('invoice', 'bill') OR "
        "(amount_paid = 0 AND amount_credited = 0 AND payment_status = 'unpaid')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_paid_through_account_id_accounts', 'documents', type_='foreignkey')
    op.drop_index('ix_documents_org_contact_phone', table_name='documents')
    op.drop_column('documents', 'paid_through_account_id')
    op.drop_column('documents', 'contact_phone')
    op.drop_column('documents', 'contact_name')
    # ### end Alembic commands ###
