"""add cnic to organizations

Revision ID: 3f805cf0e11b
Revises: 362c3d2134fc
Create Date: 2026-07-25 18:04:42.650763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f805cf0e11b'
down_revision: Union[str, None] = '362c3d2134fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('cnic', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'cnic')
    # ### end Alembic commands ###
