"""Add reference_no to accounting vouchers

Revision ID: 3faed782af59
Revises: e343ac849b09
Create Date: 2026-07-26 19:29:49.477740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faed782af59'
down_revision: Union[str, None] = 'e343ac849b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_vouchers', sa.Column('reference_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounting_vouchers', 'reference_no')
    # ### end Alembic commands ###
