"""drop per account bank branding

Revision ID: 5631ce6e038c
Revises: 68714a3a203c
Create Date: 2026-08-07 03:02:31.802818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5631ce6e038c'
down_revision: Union[str, None] = '68714a3a203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'logo_key')
    op.drop_column('bank_accounts', 'colour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('colour', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('logo_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
