"""index stock movements by source document

Revision ID: 917186906f86
Revises: b833dfe72823
Create Date: 2026-08-06 20:41:38.622894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917186906f86'
down_revision: Union[str, None] = 'b833dfe72823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stock_movements_reference', 'stock_movements', ['org_id', 'reference_type', 'reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_movements_reference', table_name='stock_movements')
    # ### end Alembic commands ###
