"""add commission payouts

Revision ID: 98fd96731777
Revises: d160bd47e6a0
Create Date: 2026-08-06 21:50:05.320147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fd96731777'
down_revision: Union[str, None] = 'd160bd47e6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_through_account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_through_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespeople.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'number', name='uq_commission_payout_org_number')
    )
    op.create_index(op.f('ix_commission_payouts_org_id'), 'commission_payouts', ['org_id'], unique=False)
    op.create_index(op.f('ix_commission_payouts_salesperson_id'), 'commission_payouts', ['salesperson_id'], unique=False)

    # Give every existing org the expense account payouts post to.
    op.execute(
        """
        INSERT INTO accounts (org_id, parent_id, code, name, account_type, normal_balance,
                              is_control_account, is_postable, is_active)
        SELECT p.org_id, p.id, '5400', 'Sales Commission', 'expense', 'debit', false, true, true
          FROM accounts p
         WHERE p.code = '5000'
           AND NOT EXISTS (
                 SELECT 1 FROM accounts a WHERE a.org_id = p.org_id AND a.code = '5400'
               )
        """
    )
    op.execute(
        """
        INSERT INTO settings (org_id, "group", key, value)
        SELECT a.org_id, 'accounting', 'sales_commission', to_jsonb(a.id)
          FROM accounts a
         WHERE a.code = '5400'
           AND NOT EXISTS (
                 SELECT 1 FROM settings s
                  WHERE s.org_id = a.org_id AND s."group" = 'accounting'
                    AND s.key = 'sales_commission'
               )
        """
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM settings WHERE \"group\" = 'accounting' AND key = 'sales_commission'"
    )
    op.execute("DELETE FROM accounts WHERE code = '5400'")
    op.drop_index(op.f('ix_commission_payouts_salesperson_id'), table_name='commission_payouts')
    op.drop_index(op.f('ix_commission_payouts_org_id'), table_name='commission_payouts')
    op.drop_table('commission_payouts')
    # ### end Alembic commands ###
