"""add fbr fields to products

Revision ID: 9cae05ef508b
Revises: 7df4628a5b77
Create Date: 2026-07-24 06:05:39.625518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cae05ef508b'
down_revision: Union[str, None] = '7df4628a5b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('hs_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('uom_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('sale_type_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('tax_rate_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tax_rate_code')
    op.drop_column('products', 'sale_type_code')
    op.drop_column('products', 'uom_code')
    op.drop_column('products', 'hs_code')
    # ### end Alembic commands ###
