"""add fbr header fields to documents

Revision ID: a5f4c1a25cde
Revises: a63d136a02c6
Create Date: 2026-07-24 23:18:46.631567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f4c1a25cde'
down_revision: Union[str, None] = 'a63d136a02c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('fbr_sale_origin', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('fbr_sale_destination', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('fbr_scenario_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'fbr_scenario_id')
    op.drop_column('documents', 'fbr_sale_destination')
    op.drop_column('documents', 'fbr_sale_origin')
    # ### end Alembic commands ###
