"""add sro fields to products

Revision ID: a63d136a02c6
Revises: 9cae05ef508b
Create Date: 2026-07-24 15:50:24.144050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63d136a02c6'
down_revision: Union[str, None] = '9cae05ef508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sro_schedule_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('sro_item_serial', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sro_item_serial')
    op.drop_column('products', 'sro_schedule_code')
    # ### end Alembic commands ###
