"""Add accounting ledger tables

Revision ID: af8c8b834bcc
Revises: fcb75baac2cb
Create Date: 2026-07-26 14:39:03.550877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8c8b834bcc'
down_revision: Union[str, None] = 'fcb75baac2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=12), nullable=False),
    sa.Column('normal_balance', sa.String(length=6), nullable=False),
    sa.Column('is_control_account', sa.Boolean(), nullable=False),
    sa.Column('is_postable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_account_org_code')
    )
    op.create_index(op.f('ix_accounts_org_id'), 'accounts', ['org_id'], unique=False)
    op.create_index('ix_accounts_org_type', 'accounts', ['org_id', 'account_type'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_fiscal_year_org_name')
    )
    op.create_index(op.f('ix_fiscal_years_org_id'), 'fiscal_years', ['org_id'], unique=False)
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'fiscal_year_id', 'period_no', name='uq_period_org_fy_no')
    )
    op.create_index(op.f('ix_accounting_periods_fiscal_year_id'), 'accounting_periods', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_accounting_periods_org_id'), 'accounting_periods', ['org_id'], unique=False)
    op.create_index('ix_periods_org_dates', 'accounting_periods', ['org_id', 'starts_on', 'ends_on'], unique=False)
    op.create_table('accounting_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('voucher_type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('reversed_from_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_from_id'], ['accounting_vouchers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'voucher_type', 'number', name='uq_voucher_org_type_number')
    )
    op.create_index(op.f('ix_accounting_vouchers_org_id'), 'accounting_vouchers', ['org_id'], unique=False)
    op.create_index('ix_vouchers_org_posting_date', 'accounting_vouchers', ['org_id', 'posting_date'], unique=False)
    op.create_index('ix_vouchers_org_source', 'accounting_vouchers', ['org_id', 'source_type', 'source_id'], unique=False)
    op.create_index('ix_vouchers_org_status', 'accounting_vouchers', ['org_id', 'status'], unique=False)
    op.create_table('voucher_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['accounting_vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voucher_lines_account', 'voucher_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_voucher_lines_voucher_id'), 'voucher_lines', ['voucher_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('voucher_line_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('voucher_type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['accounting_vouchers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_line_id'], ['voucher_lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_org_id'), 'ledger_entries', ['org_id'], unique=False)
    op.create_index('ix_ledger_org_account_posting', 'ledger_entries', ['org_id', 'account_id', 'posting_date'], unique=False)
    op.create_index('ix_ledger_org_party_posting', 'ledger_entries', ['org_id', 'party_id', 'posting_date'], unique=False)
    op.create_index('ix_ledger_org_posting', 'ledger_entries', ['org_id', 'posting_date'], unique=False)
    op.create_index('ix_ledger_org_voucher', 'ledger_entries', ['org_id', 'voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_org_voucher', table_name='ledger_entries')
    op.drop_index('ix_ledger_org_posting', table_name='ledger_entries')
    op.drop_index('ix_ledger_org_party_posting', table_name='ledger_entries')
    op.drop_index('ix_ledger_org_account_posting', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_org_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_voucher_lines_voucher_id'), table_name='voucher_lines')
    op.drop_index('ix_voucher_lines_account', table_name='voucher_lines')
    op.drop_table('voucher_lines')
    op.drop_index('ix_vouchers_org_status', table_name='accounting_vouchers')
    op.drop_index('ix_vouchers_org_source', table_name='accounting_vouchers')
    op.drop_index('ix_vouchers_org_posting_date', table_name='accounting_vouchers')
    op.drop_index(op.f('ix_accounting_vouchers_org_id'), table_name='accounting_vouchers')
    op.drop_table('accounting_vouchers')
    op.drop_index('ix_periods_org_dates', table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_org_id'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_fiscal_year_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    op.drop_index(op.f('ix_fiscal_years_org_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index('ix_accounts_org_type', table_name='accounts')
    op.drop_index(op.f('ix_accounts_org_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
