"""production baseline

Revision ID: c7f4e9a2b601
Revises:
Create Date: 2026-08-03 15:54:16.658019

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f4e9a2b601"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fbr_reference_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("value", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("parent_type", sa.String(length=30), nullable=True),
        sa.Column("parent_code", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "type", "code", "parent_code", name="uq_fbr_reference_type_code_parent"
        ),
    )
    op.create_index(
        "ix_fbr_reference_parent",
        "fbr_reference_data",
        ["parent_type", "parent_code"],
        unique=False,
    )
    op.create_index("ix_fbr_reference_type", "fbr_reference_data", ["type"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="PKR", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=2), server_default="PK", nullable=False),
        sa.Column("ntn", sa.String(length=20), nullable=True),
        sa.Column("strn", sa.String(length=20), nullable=True),
        sa.Column("cnic", sa.String(length=20), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fiscal_year_start_month", sa.Integer(), server_default="7", nullable=False),
        sa.Column("logo_url", sa.String(length=1024), nullable=True),
        sa.Column("theme", sa.String(length=10), server_default="light", nullable=False),
        sa.Column("accent_color", sa.String(length=9), server_default="#2563eb", nullable=False),
        sa.Column("keep_branding", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("fbr_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "fbr_environment", sa.String(length=12), server_default="sandbox", nullable=False
        ),
        sa.Column("fbr_sandbox_token", sa.Text(), nullable=True),
        sa.Column("fbr_production_token", sa.Text(), nullable=True),
        sa.Column("fbr_province", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_table(
        "super_admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_super_admins_email"), "super_admins", ["email"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("account_type", sa.String(length=12), nullable=False),
        sa.Column("normal_balance", sa.String(length=6), nullable=False),
        sa.Column("is_control_account", sa.Boolean(), nullable=False),
        sa.Column("is_postable", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "code", name="uq_account_org_code"),
    )
    op.create_index(op.f("ix_accounts_org_id"), "accounts", ["org_id"], unique=False)
    op.create_index("ix_accounts_org_type", "accounts", ["org_id", "account_type"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activities_org_id"), "activities", ["org_id"], unique=False)
    op.create_table(
        "attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_attribute_org_name"),
    )
    op.create_index(op.f("ix_attributes_org_id"), "attributes", ["org_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_category_org_name"),
    )
    op.create_index(op.f("ix_categories_org_id"), "categories", ["org_id"], unique=False)
    op.create_table(
        "fiscal_years",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_fiscal_year_org_name"),
    )
    op.create_index(op.f("ix_fiscal_years_org_id"), "fiscal_years", ["org_id"], unique=False)
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_org_id"), "locations", ["org_id"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("attachable_type", sa.String(length=50), nullable=False),
        sa.Column("attachable_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_assets_org_id"), "media_assets", ["org_id"], unique=False)
    op.create_index(
        "ix_media_attachable",
        "media_assets",
        ["org_id", "attachable_type", "attachable_id"],
        unique=False,
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("is_customer", sa.Boolean(), nullable=False),
        sa.Column("is_vendor", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("salutation", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.String(length=120), nullable=True),
        sa.Column("last_name", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("work_phone", sa.String(length=40), nullable=True),
        sa.Column("mobile", sa.String(length=40), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("ntn", sa.String(length=50), nullable=True),
        sa.Column("strn", sa.String(length=50), nullable=True),
        sa.Column("cnic", sa.String(length=20), nullable=True),
        sa.Column("payment_term_days", sa.Integer(), nullable=True),
        sa.Column("billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("shipping_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_parties_org_customer", "parties", ["org_id", "is_customer"], unique=False)
    op.create_index(op.f("ix_parties_org_id"), "parties", ["org_id"], unique=False)
    op.create_index("ix_parties_org_vendor", "parties", ["org_id", "is_vendor"], unique=False)
    op.create_table(
        "reasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_reason_org_name"),
    )
    op.create_index(op.f("ix_reasons_org_id"), "reasons", ["org_id"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_sessions_family_id"), "refresh_sessions", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_sessions_token_hash"), "refresh_sessions", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "slug", name="uq_role_org_slug"),
    )
    op.create_index(op.f("ix_roles_org_id"), "roles", ["org_id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("group", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "group", "key", name="uq_setting_org_group_key"),
    )
    op.create_index("ix_settings_org_group", "settings", ["org_id", "group"], unique=False)
    op.create_index(op.f("ix_settings_org_id"), "settings", ["org_id"], unique=False)
    op.create_table(
        "super_admin_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["super_admins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_super_admin_sessions_admin_id"), "super_admin_sessions", ["admin_id"], unique=False
    )
    op.create_index(
        op.f("ix_super_admin_sessions_family_id"),
        "super_admin_sessions",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_super_admin_sessions_token_hash"),
        "super_admin_sessions",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "tax_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("rate", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_tax_rate_org_name"),
    )
    op.create_index(op.f("ix_tax_rates_org_id"), "tax_rates", ["org_id"], unique=False)
    op.create_table(
        "uoms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_uom_org_name"),
    )
    op.create_index(op.f("ix_uoms_org_id"), "uoms", ["org_id"], unique=False)
    op.create_table(
        "accounting_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_year_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("period_no", sa.Integer(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fiscal_year_id"], ["fiscal_years.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "fiscal_year_id", "period_no", name="uq_period_org_fy_no"),
    )
    op.create_index(
        op.f("ix_accounting_periods_fiscal_year_id"),
        "accounting_periods",
        ["fiscal_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounting_periods_org_id"), "accounting_periods", ["org_id"], unique=False
    )
    op.create_index(
        "ix_periods_org_dates",
        "accounting_periods",
        ["org_id", "starts_on", "ends_on"],
        unique=False,
    )
    op.create_table(
        "attribute_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("attribute_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["attribute_id"], ["attributes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attribute_id", "value", name="uq_attrvalue_attr_value"),
    )
    op.create_index(
        op.f("ix_attribute_values_attribute_id"), "attribute_values", ["attribute_id"], unique=False
    )
    op.create_index(
        op.f("ix_attribute_values_org_id"), "attribute_values", ["org_id"], unique=False
    )
    op.create_table(
        "bins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "location_id", "code", name="uq_bin_location_code"),
    )
    op.create_index(op.f("ix_bins_org_id"), "bins", ["org_id"], unique=False)
    op.create_index("ix_bins_org_location", "bins", ["org_id", "location_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("expected_shipment_date", sa.Date(), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("shipping_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fbr_sale_origin", sa.String(length=50), nullable=True),
        sa.Column("fbr_sale_destination", sa.String(length=50), nullable=True),
        sa.Column("fbr_scenario_id", sa.String(length=20), nullable=True),
        sa.Column("fbr_reason", sa.String(length=100), nullable=True),
        sa.Column("fbr_reason_remarks", sa.String(length=255), nullable=True),
        sa.Column("fbr_invoice_number", sa.String(length=64), nullable=True),
        sa.Column("fbr_submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fbr_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "further_tax_total",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("shipping", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("adjustment", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("payment_status", sa.String(length=10), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("stock_posted", sa.Boolean(), nullable=False),
        sa.Column("settled_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "type = 'credit_note' OR (fbr_reason IS NULL AND fbr_reason_remarks IS NULL)",
            name="ck_documents_fbr_reason_type",
        ),
        sa.CheckConstraint(
            "type = 'credit_note' OR settled_amount = 0", name="ck_documents_settlement_type"
        ),
        sa.CheckConstraint(
            "type = 'sales_order' OR expected_shipment_date IS NULL",
            name="ck_documents_expected_shipment_type",
        ),
        sa.CheckConstraint(
            "type IN ('invoice', 'bill') OR (amount_paid = 0 AND payment_status = 'unpaid')",
            name="ck_documents_payment_fields_type",
        ),
        sa.CheckConstraint(
            "type IN ('invoice', 'bill') OR due_date IS NULL", name="ck_documents_due_date_type"
        ),
        sa.CheckConstraint(
            "type IN ('invoice', 'credit_note') OR "
            "(fbr_sale_origin IS NULL AND fbr_sale_destination IS NULL "
            "AND fbr_scenario_id IS NULL AND fbr_invoice_number IS NULL "
            "AND fbr_submitted_at IS NULL AND fbr_response IS NULL)",
            name="ck_documents_fbr_fields_type",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["party_id"], ["parties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "type", "number", name="uq_document_org_type_number"),
    )
    op.create_index(op.f("ix_documents_org_id"), "documents", ["org_id"], unique=False)
    op.create_index("ix_documents_org_party", "documents", ["org_id", "party_id"], unique=False)
    op.create_index("ix_documents_org_type", "documents", ["org_id", "type"], unique=False)
    op.create_index(op.f("ix_documents_party_id"), "documents", ["party_id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("paid_through_account_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("vendor_name", sa.String(length=255), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("is_tax_inclusive", sa.Boolean(), nullable=False),
        sa.Column("reference_no", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cancelled_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["parties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["paid_through_account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["submitted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["parties.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "number", name="uq_expense_org_number"),
    )
    op.create_index("ix_expenses_org_date", "expenses", ["org_id", "expense_date"], unique=False)
    op.create_index(op.f("ix_expenses_org_id"), "expenses", ["org_id"], unique=False)
    op.create_index("ix_expenses_org_status", "expenses", ["org_id", "status"], unique=False)
    op.create_index(op.f("ix_expenses_vendor_id"), "expenses", ["vendor_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "org_id", name="uq_membership_user_org"),
    )
    op.create_index(op.f("ix_memberships_org_id"), "memberships", ["org_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("party_name", sa.String(length=255), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unapplied_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cancelled_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["party_id"], ["parties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["submitted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id", "direction", "number", name="uq_payment_org_direction_number"
        ),
    )
    op.create_index("ix_payments_org_direction", "payments", ["org_id", "direction"], unique=False)
    op.create_index(op.f("ix_payments_org_id"), "payments", ["org_id"], unique=False)
    op.create_index("ix_payments_org_party", "payments", ["org_id", "party_id"], unique=False)
    op.create_index(op.f("ix_payments_party_id"), "payments", ["party_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("nature", sa.String(length=20), server_default="good", nullable=False),
        sa.Column("type", sa.String(length=20), server_default="single", nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("hs_code", sa.String(length=20), nullable=True),
        sa.Column("uom_code", sa.String(length=20), nullable=True),
        sa.Column("sale_type_code", sa.String(length=20), nullable=True),
        sa.Column("tax_rate_code", sa.String(length=20), nullable=True),
        sa.Column("sro_schedule_code", sa.String(length=20), nullable=True),
        sa.Column("sro_item_serial", sa.String(length=30), nullable=True),
        sa.Column("track_inventory", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tracking_mode", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("reorder_point", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uom_id"], ["uoms.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "sku", name="uq_product_org_sku"),
    )
    op.create_index(op.f("ix_products_org_id"), "products", ["org_id"], unique=False)
    op.create_index(op.f("ix_products_parent_id"), "products", ["parent_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "accounting_vouchers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_year_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("voucher_type", sa.String(length=20), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("reference_no", sa.String(length=50), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by_id", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Integer(), nullable=True),
        sa.Column("reversed_from_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cancelled_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fiscal_year_id"], ["fiscal_years.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["period_id"], ["accounting_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["posted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["reversed_from_id"], ["accounting_vouchers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "voucher_type", "number", name="uq_voucher_org_type_number"),
    )
    op.create_index(
        op.f("ix_accounting_vouchers_org_id"), "accounting_vouchers", ["org_id"], unique=False
    )
    op.create_index(
        "ix_vouchers_org_posting_date",
        "accounting_vouchers",
        ["org_id", "posting_date"],
        unique=False,
    )
    op.create_index(
        "ix_vouchers_org_source",
        "accounting_vouchers",
        ["org_id", "source_type", "source_id"],
        unique=False,
    )
    op.create_index(
        "ix_vouchers_org_status", "accounting_vouchers", ["org_id", "status"], unique=False
    )
    op.create_table(
        "document_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("bin_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_type", sa.String(length=10), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_rate_id", sa.Integer(), nullable=True),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "further_tax", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bin_id"], ["bins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tax_rate_id"], ["tax_rates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_lines_document_id"), "document_lines", ["document_id"], unique=False
    )
    op.create_table(
        "expense_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_expense_lines_account", "expense_lines", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_expense_lines_expense_id"), "expense_lines", ["expense_id"], unique=False
    )
    op.create_table(
        "fbr_submission_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fbr_submission_attempts_document_id"),
        "fbr_submission_attempts",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_fbr_submission_attempts_org_created",
        "fbr_submission_attempts",
        ["org_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fbr_submission_attempts_org_id"),
        "fbr_submission_attempts",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        "ix_fbr_submission_attempts_status", "fbr_submission_attempts", ["status"], unique=False
    )
    op.create_table(
        "payment_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("document_number", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "payment_id", "document_id", name="uq_payment_allocation_payment_document"
        ),
    )
    op.create_index(
        op.f("ix_payment_allocations_document_id"),
        "payment_allocations",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_id"),
        "payment_allocations",
        ["payment_id"],
        unique=False,
    )
    op.create_table(
        "product_attribute_values",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("attribute_value_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"], ["attribute_values.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "attribute_value_id"),
    )
    op.create_table(
        "serial_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("serial_number", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("bin_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["bin_id"], ["bins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id", "product_id", "serial_number", name="uq_serial_unit_product_number"
        ),
    )
    op.create_index(op.f("ix_serial_units_org_id"), "serial_units", ["org_id"], unique=False)
    op.create_index(
        "ix_serial_units_org_product_status",
        "serial_units",
        ["org_id", "product_id", "status"],
        unique=False,
    )
    op.create_table(
        "stock_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("lot_number", sa.String(length=100), nullable=False),
        sa.Column("manufactured_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id", "product_id", "lot_number", name="uq_stock_lot_product_number"
        ),
    )
    op.create_index(op.f("ix_stock_lots_org_id"), "stock_lots", ["org_id"], unique=False)
    op.create_index(
        "ix_stock_lots_org_product", "stock_lots", ["org_id", "product_id"], unique=False
    )
    op.create_table(
        "variant_values",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("attribute_value_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"], ["attribute_values.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "attribute_value_id"),
    )
    op.create_table(
        "document_line_lot_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_line_id", sa.Integer(), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.ForeignKeyConstraint(["document_line_id"], ["document_lines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["stock_lots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_line_id", "lot_id", name="uq_document_line_lot"),
    )
    op.create_index(
        op.f("ix_document_line_lot_allocations_document_line_id"),
        "document_line_lot_allocations",
        ["document_line_id"],
        unique=False,
    )
    op.create_table(
        "document_line_serials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_line_id", sa.Integer(), nullable=False),
        sa.Column("serial_number", sa.String(length=150), nullable=False),
        sa.Column("serial_unit_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["document_line_id"], ["document_lines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["serial_unit_id"], ["serial_units.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_line_id", "serial_number", name="uq_document_line_serial"),
    )
    op.create_index(
        op.f("ix_document_line_serials_document_line_id"),
        "document_line_serials",
        ["document_line_id"],
        unique=False,
    )
    op.create_table(
        "stock_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("bin_id", sa.Integer(), nullable=True),
        sa.Column("lot_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bin_id"], ["bins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["stock_lots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_levels_bin_id"), "stock_levels", ["bin_id"], unique=False)
    op.create_index(op.f("ix_stock_levels_lot_id"), "stock_levels", ["lot_id"], unique=False)
    op.create_index(op.f("ix_stock_levels_org_id"), "stock_levels", ["org_id"], unique=False)
    op.create_index(
        "ix_stock_levels_org_product", "stock_levels", ["org_id", "product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_levels_product_id"), "stock_levels", ["product_id"], unique=False
    )
    op.create_index(
        "uq_stock_level_binned_lotted",
        "stock_levels",
        ["org_id", "product_id", "location_id", "bin_id", "lot_id"],
        unique=True,
        postgresql_where=sa.text("bin_id IS NOT NULL AND lot_id IS NOT NULL"),
    )
    op.create_index(
        "uq_stock_level_binned_unlotted",
        "stock_levels",
        ["org_id", "product_id", "location_id", "bin_id"],
        unique=True,
        postgresql_where=sa.text("bin_id IS NOT NULL AND lot_id IS NULL"),
    )
    op.create_index(
        "uq_stock_level_unbinned_lotted",
        "stock_levels",
        ["org_id", "product_id", "location_id", "lot_id"],
        unique=True,
        postgresql_where=sa.text("bin_id IS NULL AND lot_id IS NOT NULL"),
    )
    op.create_index(
        "uq_stock_level_unbinned_unlotted",
        "stock_levels",
        ["org_id", "product_id", "location_id"],
        unique=True,
        postgresql_where=sa.text("bin_id IS NULL AND lot_id IS NULL"),
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("bin_id", sa.Integer(), nullable=True),
        sa.Column("lot_id", sa.Integer(), nullable=True),
        sa.Column("qty_delta", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("value_delta", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["bin_id"], ["bins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["stock_lots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_movements_bin_id"), "stock_movements", ["bin_id"], unique=False)
    op.create_index(op.f("ix_stock_movements_lot_id"), "stock_movements", ["lot_id"], unique=False)
    op.create_index(op.f("ix_stock_movements_org_id"), "stock_movements", ["org_id"], unique=False)
    op.create_index(
        "ix_stock_movements_org_product", "stock_movements", ["org_id", "product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_product_id"), "stock_movements", ["product_id"], unique=False
    )
    op.create_table(
        "voucher_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voucher_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["party_id"], ["parties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["voucher_id"], ["accounting_vouchers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_voucher_lines_account", "voucher_lines", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_voucher_lines_voucher_id"), "voucher_lines", ["voucher_id"], unique=False
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("voucher_id", sa.Integer(), nullable=False),
        sa.Column("voucher_line_id", sa.Integer(), nullable=True),
        sa.Column("fiscal_year_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("voucher_type", sa.String(length=20), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fiscal_year_id"], ["fiscal_years.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["party_id"], ["parties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["period_id"], ["accounting_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["voucher_id"], ["accounting_vouchers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["voucher_line_id"], ["voucher_lines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ledger_entries_org_id"), "ledger_entries", ["org_id"], unique=False)
    op.create_index(
        "ix_ledger_org_account_posting",
        "ledger_entries",
        ["org_id", "account_id", "posting_date"],
        unique=False,
    )
    op.create_index(
        "ix_ledger_org_party_posting",
        "ledger_entries",
        ["org_id", "party_id", "posting_date"],
        unique=False,
    )
    op.create_index(
        "ix_ledger_org_posting", "ledger_entries", ["org_id", "posting_date"], unique=False
    )
    op.create_index(
        "ix_ledger_org_voucher", "ledger_entries", ["org_id", "voucher_id"], unique=False
    )
    op.create_table(
        "stock_movement_serials",
        sa.Column("movement_id", sa.Integer(), nullable=False),
        sa.Column("serial_unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["movement_id"], ["stock_movements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["serial_unit_id"], ["serial_units.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("movement_id", "serial_unit_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_movement_serials")
    op.drop_index("ix_ledger_org_voucher", table_name="ledger_entries")
    op.drop_index("ix_ledger_org_posting", table_name="ledger_entries")
    op.drop_index("ix_ledger_org_party_posting", table_name="ledger_entries")
    op.drop_index("ix_ledger_org_account_posting", table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_org_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_voucher_lines_voucher_id"), table_name="voucher_lines")
    op.drop_index("ix_voucher_lines_account", table_name="voucher_lines")
    op.drop_table("voucher_lines")
    op.drop_index(op.f("ix_stock_movements_product_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_org_product", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_org_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_lot_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_bin_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(
        "uq_stock_level_unbinned_unlotted",
        table_name="stock_levels",
        postgresql_where=sa.text("bin_id IS NULL AND lot_id IS NULL"),
    )
    op.drop_index(
        "uq_stock_level_unbinned_lotted",
        table_name="stock_levels",
        postgresql_where=sa.text("bin_id IS NULL AND lot_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_stock_level_binned_unlotted",
        table_name="stock_levels",
        postgresql_where=sa.text("bin_id IS NOT NULL AND lot_id IS NULL"),
    )
    op.drop_index(
        "uq_stock_level_binned_lotted",
        table_name="stock_levels",
        postgresql_where=sa.text("bin_id IS NOT NULL AND lot_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_stock_levels_product_id"), table_name="stock_levels")
    op.drop_index("ix_stock_levels_org_product", table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_org_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_lot_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_bin_id"), table_name="stock_levels")
    op.drop_table("stock_levels")
    op.drop_index(
        op.f("ix_document_line_serials_document_line_id"), table_name="document_line_serials"
    )
    op.drop_table("document_line_serials")
    op.drop_index(
        op.f("ix_document_line_lot_allocations_document_line_id"),
        table_name="document_line_lot_allocations",
    )
    op.drop_table("document_line_lot_allocations")
    op.drop_table("variant_values")
    op.drop_index("ix_stock_lots_org_product", table_name="stock_lots")
    op.drop_index(op.f("ix_stock_lots_org_id"), table_name="stock_lots")
    op.drop_table("stock_lots")
    op.drop_index("ix_serial_units_org_product_status", table_name="serial_units")
    op.drop_index(op.f("ix_serial_units_org_id"), table_name="serial_units")
    op.drop_table("serial_units")
    op.drop_table("product_attribute_values")
    op.drop_index(op.f("ix_payment_allocations_payment_id"), table_name="payment_allocations")
    op.drop_index(op.f("ix_payment_allocations_document_id"), table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index("ix_fbr_submission_attempts_status", table_name="fbr_submission_attempts")
    op.drop_index(op.f("ix_fbr_submission_attempts_org_id"), table_name="fbr_submission_attempts")
    op.drop_index("ix_fbr_submission_attempts_org_created", table_name="fbr_submission_attempts")
    op.drop_index(
        op.f("ix_fbr_submission_attempts_document_id"), table_name="fbr_submission_attempts"
    )
    op.drop_table("fbr_submission_attempts")
    op.drop_index(op.f("ix_expense_lines_expense_id"), table_name="expense_lines")
    op.drop_index("ix_expense_lines_account", table_name="expense_lines")
    op.drop_table("expense_lines")
    op.drop_index(op.f("ix_document_lines_document_id"), table_name="document_lines")
    op.drop_table("document_lines")
    op.drop_index("ix_vouchers_org_status", table_name="accounting_vouchers")
    op.drop_index("ix_vouchers_org_source", table_name="accounting_vouchers")
    op.drop_index("ix_vouchers_org_posting_date", table_name="accounting_vouchers")
    op.drop_index(op.f("ix_accounting_vouchers_org_id"), table_name="accounting_vouchers")
    op.drop_table("accounting_vouchers")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_products_parent_id"), table_name="products")
    op.drop_index(op.f("ix_products_org_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_payments_party_id"), table_name="payments")
    op.drop_index("ix_payments_org_party", table_name="payments")
    op.drop_index(op.f("ix_payments_org_id"), table_name="payments")
    op.drop_index("ix_payments_org_direction", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_org_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_expenses_vendor_id"), table_name="expenses")
    op.drop_index("ix_expenses_org_status", table_name="expenses")
    op.drop_index(op.f("ix_expenses_org_id"), table_name="expenses")
    op.drop_index("ix_expenses_org_date", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_documents_party_id"), table_name="documents")
    op.drop_index("ix_documents_org_type", table_name="documents")
    op.drop_index("ix_documents_org_party", table_name="documents")
    op.drop_index(op.f("ix_documents_org_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_bins_org_location", table_name="bins")
    op.drop_index(op.f("ix_bins_org_id"), table_name="bins")
    op.drop_table("bins")
    op.drop_index(op.f("ix_attribute_values_org_id"), table_name="attribute_values")
    op.drop_index(op.f("ix_attribute_values_attribute_id"), table_name="attribute_values")
    op.drop_table("attribute_values")
    op.drop_index("ix_periods_org_dates", table_name="accounting_periods")
    op.drop_index(op.f("ix_accounting_periods_org_id"), table_name="accounting_periods")
    op.drop_index(op.f("ix_accounting_periods_fiscal_year_id"), table_name="accounting_periods")
    op.drop_table("accounting_periods")
    op.drop_index(op.f("ix_uoms_org_id"), table_name="uoms")
    op.drop_table("uoms")
    op.drop_index(op.f("ix_tax_rates_org_id"), table_name="tax_rates")
    op.drop_table("tax_rates")
    op.drop_index(op.f("ix_super_admin_sessions_token_hash"), table_name="super_admin_sessions")
    op.drop_index(op.f("ix_super_admin_sessions_family_id"), table_name="super_admin_sessions")
    op.drop_index(op.f("ix_super_admin_sessions_admin_id"), table_name="super_admin_sessions")
    op.drop_table("super_admin_sessions")
    op.drop_index(op.f("ix_settings_org_id"), table_name="settings")
    op.drop_index("ix_settings_org_group", table_name="settings")
    op.drop_table("settings")
    op.drop_index(op.f("ix_roles_org_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_token_hash"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_family_id"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_reasons_org_id"), table_name="reasons")
    op.drop_table("reasons")
    op.drop_index("ix_parties_org_vendor", table_name="parties")
    op.drop_index(op.f("ix_parties_org_id"), table_name="parties")
    op.drop_index("ix_parties_org_customer", table_name="parties")
    op.drop_table("parties")
    op.drop_index("ix_media_attachable", table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_org_id"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_locations_org_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_fiscal_years_org_id"), table_name="fiscal_years")
    op.drop_table("fiscal_years")
    op.drop_index(op.f("ix_categories_org_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_attributes_org_id"), table_name="attributes")
    op.drop_table("attributes")
    op.drop_index(op.f("ix_activities_org_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_index("ix_accounts_org_type", table_name="accounts")
    op.drop_index(op.f("ix_accounts_org_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_super_admins_email"), table_name="super_admins")
    op.drop_table("super_admins")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index("ix_fbr_reference_type", table_name="fbr_reference_data")
    op.drop_index("ix_fbr_reference_parent", table_name="fbr_reference_data")
    op.drop_table("fbr_reference_data")
    # ### end Alembic commands ###
