"""add fbr reason to documents

Revision ID: cbf3a37605af
Revises: 3f805cf0e11b
Create Date: 2026-07-25 19:14:25.952014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf3a37605af'
down_revision: Union[str, None] = '3f805cf0e11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('fbr_reason', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('fbr_reason_remarks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'fbr_reason_remarks')
    op.drop_column('documents', 'fbr_reason')
    # ### end Alembic commands ###
