"""add salespeople and commission

Revision ID: d160bd47e6a0
Revises: ab46e30d4c67
Create Date: 2026-08-06 21:33:00.786683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd160bd47e6a0'
down_revision: Union[str, None] = 'ab46e30d4c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salespeople',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=6, scale=3), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_salesperson_org_name')
    )
    op.create_index(op.f('ix_salespeople_org_id'), 'salespeople', ['org_id'], unique=False)
    op.add_column('documents', sa.Column('salesperson_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('commission_rate', sa.Numeric(precision=6, scale=3), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.create_index(op.f('ix_documents_salesperson_id'), 'documents', ['salesperson_id'], unique=False)
    op.create_foreign_key(
        'fk_documents_salesperson_id_salespeople', 'documents', 'salespeople',
        ['salesperson_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_salesperson_id_salespeople', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_salesperson_id'), table_name='documents')
    op.drop_column('documents', 'commission_amount')
    op.drop_column('documents', 'commission_rate')
    op.drop_column('documents', 'salesperson_id')
    op.drop_index(op.f('ix_salespeople_org_id'), table_name='salespeople')
    op.drop_table('salespeople')
    # ### end Alembic commands ###
