"""Add value_delta to stock movements

Revision ID: e343ac849b09
Revises: af8c8b834bcc
Create Date: 2026-07-26 16:48:37.729386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e343ac849b09'
down_revision: Union[str, None] = 'af8c8b834bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('value_delta', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'value_delta')
    # ### end Alembic commands ###
