"""add storage_key to media_assets

Revision ID: fcb75baac2cb
Revises: cbf3a37605af
Create Date: 2026-07-25 21:08:26.976671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb75baac2cb'
down_revision: Union[str, None] = 'cbf3a37605af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('storage_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'storage_key')
    # ### end Alembic commands ###
